### ISSUE TITLE
河北专业技术人员求适配

### ISSUE THREAD

**Issue by Dave0424** [yikuaibaiban/chinahrt-autoplay#10]
https://hbzyjs.chinahrt.com插件的三段式和拖动功能不稳定，偶尔能用下就不能用了。
账号:dongzongbao
密:shan199104247113

**Comment by yikuaibaiban** [comment]
关于多段式的播放，这个功能是一个小众地区的BUG方式调用，并非所有地区都可以适配。
拖动功能这边没遇到你所说的问题，考虑使用EDGE，Chrome等浏览器试下？
如果问题没有解决，可以通过博客园的私信功能发送，避免账号密码泄露导致不必要的麻烦

**Comment by kkk15238** [comment]
安阳继续教育求适配

**Comment by yikuaibaiban** [comment]
> 安阳继续教育求适配
可以描述下问题或者通过博客园等私信账号密码？

**Comment by kkk15238** [comment]
学完一个课时后下个视频无法跳转

**Comment by Dave0424** [comment]
我已收到您的邮件，谢谢。

**Comment by kkk15238** [comment]
手动跳转后再次学完还是无法跳转
