### ISSUE TITLE
安阳继续教育网

### ISSUE THREAD

**Issue by kkk15238** [yikuaibaiban/chinahrt-autoplay#11]

**Comment by yikuaibaiban** [comment]
脚本在检测到播放完成后会自动跳转到下一个播放地址的。
如果刷新页面极有可能会导致重新播放当前的视频。

**Comment by kkk15238** [comment]
b播放完当前视频无法正常打开下一个视频播放求适配

**Comment by kkk15238** [comment]
410581199901209139  FHCfhc@521

**Comment by kkk15238** [comment]
求解决

**Comment by robinvicky** [comment]
可以添加课程，但是一个课程结束后无法连续播放，需要再次手动点击开始才行。

**Comment by yikuaibaiban** [comment]
> 可以添加课程，但是一个课程结束后无法连续播放，需要再次手动点击开始才行。

可以查实下新版本，程序逻辑应该更加清晰。
调整了失去焦点的代码，我这边测试已经不会出现失去焦点就暂停的问题。
