### ISSUE TITLE
四川的继续教育，播放完到下一个可能就不放了

### ISSUE THREAD

**Issue by yang478** [yikuaibaiban/chinahrt-autoplay#2]
播放完一个视频到下一个可能就不放了，同时右边的视频控制配置也不见了

**Comment by yikuaibaiban** [comment]
造成这个的原因可能是播放页面的地址不再是脚本能匹配的地址。
如果遇到这个问题，可以把播放器的地址发出来么？
他是在iframe上的一个地址

**Comment by yang478** [comment]
又遇到这个情况了。

`<iframe data-v-203b5c6f="" allowfullscreen="allowfullscreen" border="0" src="https://videoadmin.chinahrt.com/videoPlay/play?business_id=gp5&amp;signId=151%23f2c16584e5ef40b5821250309dd9238a%23df032ad0df864bf79f617033a9f2e4e8&amp;courseId=44b0ff7303cc4e8dab6d8ce516ccb94d&amp;sectionId=44b0ff7303cc4e8dab6d8ce516ccb94d1-1&amp;ifPauseAd=1&amp;ifPauseBlur=1&amp;ifCourseComplete=0&amp;ifDrag=0&amp;proxy_url=https://web.chinahrt.com/index.html%23/v_proxy%3FtrainplanId=f2c16584e5ef40b5821250309dd9238a%26courseId=44b0ff7303cc4e8dab6d8ce516ccb94d%26sectionId=44b0ff7303cc4e8dab6d8ce516ccb94d1-1&amp;receive_course_record_url=https://yun.chinahrt.com/yunapi/course/update_learn_record&amp;version=ckplayerx1&amp;sub_domain_name=151&amp;allow_study_same_time=0" id="iframe" style="width: 100%; border: none; height: 1007px;"></iframe>`

**Comment by yang478** [comment]
对应的video id是下面这个
`<video id="chvyqsrpptqbnlwhtx" src="https://video.chinahrt.com/u/u/courseyun/gp5/transcode/20227/22aeb731-984d-417f-a6cd-e65f81e9210c/283001-mp4.mp4" width="100%" height="100%" style="width: 100%; height: 100%; background-color: rgb(0, 0, 0);" jm_neat="439984129"></video>`
