### ISSUE TITLE
关于chinhrt在宁波地区无法出现配置界面和播放列表

### ISSUE THREAD

**Issue by ghost** [yikuaibaiban/chinahrt-autoplay#4]
同样是dota爱好者  jugg 最近搞这个继续教育 还好发现你的神器  方便留个邮箱吗

**Comment by jeavenchu** [comment]
同宁波地区 可以出现视频控制配置，但是在课程页那边无法添加视频，视频列表为空

**Comment by jeavenchu** [comment]
> 同宁波地区 可以出现视频控制配置，但是在课程页那边无法添加视频，视频列表为空

刚刚尝试用edge发现可以添加课程列表，我原来用的是chrome
