### ISSUE TITLE
 希望增加功能

### ISSUE THREAD

**Issue by EvilCY** [yikuaibaiban/chinahrt-autoplay#5]
希望增加功能，视频分成前中后三个部分播放，前播放一分半，移动到中间播放一分半，末尾播放一分半，这样播放完成后，在随机播放一个视频的末尾一分半后食品街学完了。这个是这个平台的bug，如果没理解可以回复我

**Comment by yikuaibaiban** [comment]
你这个意思是，将视频分成三段，再播放三段各自的前一分半时间，最后播放第三段的结尾一分半。是这个意思么？

**Comment by yikuaibaiban** [comment]
> 希望增加功能，视频分成前中后三个部分播放，前播放一分半，移动到中间播放一分半，末尾播放一分半，这样播放完成后，在随机播放一个视频的末尾一分半后食品街学完了。这个是这个平台的bug，如果没理解可以回复我

已经增加了三段播放模式，可更新脚本查看下

**Comment by yikuaibaiban** [comment]
> 希望增加功能，视频分成前中后三个部分播放，前播放一分半，移动到中间播放一分半，末尾播放一分半，这样播放完成后，在随机播放一个视频的末尾一分半后食品街学完了。这个是这个平台的bug，如果没理解可以回复我

已经增加了三段播放模式，可更新脚本查看下

**Comment by yizhixiaobaimiaomiaomiao** [comment]
> 希望增加功能，视频分成前中后三个部分播放，前播放一分半，移动到中间播放一分半，末尾播放一分半，这样播放完成后，在随机播放一个视频的末尾一分半后食品街学完了。这个是这个平台的bug，如果没理解可以回复我

好像确实是这样，去年能用加速听的时候好像就是这个规律，前中后，最后还要播一遍末尾就100%了
