### ISSUE TITLE
甘肃只能实现自动播放，不能添加播放列表。

### ISSUE THREAD

**Issue by AppLe-NeMo** [yikuaibaiban/chinahrt-autoplay#9]
按“教程”里面的视频预览地址类似(web.chinahrt.com/course/preview?courseId=&trainplanId=)，
 但是甘肃的地址是（gp.chinahrt.com/index.html#/v_courseDetails?courseId=XXXXXXXXXXXX&trainplanId=XXXXXXXXXXX&platformId=XXX&fromPage=selected）这样的。

**Comment by yikuaibaiban** [comment]
已经针对地址 （gp.chinahrt.com/index.html#/v_courseDetails?courseId=XXXXXXXXXXXX&trainplanId=XXXXXXXXXXX&platformId=XXX&fromPage=selected）进行（#/v_courseDetails）匹配。
剩余功能是否可以正常匹配还不清楚（无法验证），更新后您可以常识看下是否能正常使用，如果不能正常使用可以通过博客园等私信我账号密码，请尽量避免账号密码的泄露。
会在晚些时候进行更新。
